import i18next from '@/i18n';

// Portfolio Images
import img1 from '@/assets/images/portfolioIMG/portfolioImg1.webp';
import img2 from '@/assets/images/portfolioIMG/portfolioImg2.webp';
import img3 from '@/assets/images/portfolioIMG/portfolioImg3.webp';
import img4 from '@/assets/images/portfolioIMG/portfolioImg4.webp';
import img5 from '@/assets/images/portfolioIMG/portfolioImg5.webp';
import img6 from '@/assets/images/portfolioIMG/portfolioImg6.webp';
import img7 from '@/assets/images/portfolioIMG/portfolioImg7.webp';
import img8 from '@/assets/images/portfolioIMG/portfolioImg8.webp';
import img9 from '@/assets/images/portfolioIMG/portfolioImg9.webp';
import img10 from '@/assets/images/portfolioIMG/portfolioImg10.webp';
import img11 from '@/assets/images/portfolioIMG/portfolioImg11.webp';
import img12 from '@/assets/images/portfolioIMG/portfolioImg12.webp';

export const portfolioCard = [
    {
        id: 12,
        title: 'portfolioCard.title.title12',
        subTitle: 'portfolioCard.subTitle',
        year: '2025',
        design: '+',
        role: 'portfolioCard.role1',
        tag: 'React.js, SCSS, JS, BEM',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type2',
        url: 'https://andrey2528.github.io/GrillCalc/',
        img: img12,
        description: 'portfolioCard.description.description12',
        timeToEndWork: '3 portfolioCard.timeWork.Hours',
    },
    {
        id: 11,
        title: 'portfolioCard.title.title11',
        subTitle: 'portfolioCard.subTitle',
        year: '2025',
        design: '-',
        role: 'portfolioCard.role1',
        tag: 'React.js, SCSS, JS, BEM, SEO',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type3',
        url: 'https://andrey2528.github.io/PortfolioAZ/#/',
        img: img11,
        description: 'portfolioCard.description.description11',
        timeToEndWork: '20 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 10,
        title: 'portfolioCard.title.title9',
        subTitle: 'portfolioCard.subTitle',
        year: '2024',
        design: '-',
        role: 'portfolioCard.role1',
        tag: 'HTML, CSS, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform1',
        type: 'portfolioCard.type3',
        url: 'portfolioCard.urlNotAviable',
        img: img9,
        description: 'portfolioCard.description.description9',
        timeToEndWork: '30 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 9,
        title: 'portfolioCard.title.title10',
        subTitle: 'portfolioCard.subTitle',
        year: '2023',
        design: '+',
        role: 'portfolioCard.role1',
        tag: 'HTML, CSS, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform1',
        type: 'portfolioCard.type3',
        url: 'https://andrey2528.github.io/1_drop_socks/',
        img: img10,
        description: 'portfolioCard.description.description10',
        timeToEndWork: '7 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 8,
        title: 'portfolioCard.title.title8',
        subTitle: 'portfolioCard.subTitle',
        year: '2023',
        design: '-',
        role: 'portfolioCard.role1',
        tag: 'HTML, CSS, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform1',
        type: 'portfolioCard.type3',
        url: 'http://sketch2site.com',
        img: img8,
        description: 'portfolioCard.description.description8',
        timeToEndWork: '30 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 7,
        title: 'portfolioCard.title.title7',
        subTitle: 'portfolioCard.subTitle',
        year: '2023',
        design: '-',
        role: 'portfolioCard.role1, portfolioCard.role2',
        tag: 'HTML, CSS, PHP, WordPress, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type1',
        url: 'http://batumikarting.ge',
        img: img7,
        description: 'portfolioCard.description.description7',
        timeToEndWork: '200 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 6,
        title: 'portfolioCard.title.title6',
        subTitle: 'portfolioCard.subTitle',
        year: '2022',
        design: '-',
        role: 'portfolioCard.role1, portfolioCard.role3, portfolioCard.role4',
        tag: 'HTML, SCSS, JS, React.js, BEM',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type2',
        url: 'portfolioCard.urlNotAviable',
        img: img6,
        description: 'portfolioCard.description.description6',
        timeToEndWork: '15 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 5,
        title: 'portfolioCard.title.title5',
        subTitle: 'portfolioCard.subTitle',
        year: '2022',
        design: '-',
        role: 'portfolioCard.role1, portfolioCard.role3, portfolioCard.role4',
        tag: 'HTML, CSS, PHP, WordPress, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type3',
        img: img5,
        description: 'portfolioCard.description.description5',
        timeToEndWork: '100 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 4,
        title: 'portfolioCard.title.title4',
        subTitle: 'portfolioCard.subTitle',
        year: '2022',
        design: '-',
        role: 'portfolioCard.role1, portfolioCard.role3',
        tag: 'HTML, CSS, JS, jQuery, BEM',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type2',
        url: 'https://andrey2528.github.io/people-taback/',
        img: img4,
        description: 'portfolioCard.description.description4',
        timeToEndWork: '9 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 3,
        title: 'portfolioCard.title.title3',
        subTitle: 'portfolioCard.subTitle',
        year: '2022',
        design: '-',
        role: 'portfolioCard.role1, portfolioCard.role3, portfolioCard.role4',
        tag: 'HTML, CSS, JS, jQuery, BEM, SEO',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type3',
        url: 'https://fairpartner.pl/',
        img: img3,
        description: 'portfolioCard.description.description3',
        timeToEndWork: '20 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 2,
        title: 'portfolioCard.title.title2',
        subTitle: 'portfolioCard.subTitle',
        year: '2019',
        design: '-',
        role: 'portfolioCard.role1',
        tag: 'HTML, CSS, JS, jQuery, BEM',
        platform: 'portfolioCard.platform2',
        type: 'portfolioCard.type2',
        url: 'portfolioCard.urlNotAviable',
        img: img2,
        description: 'portfolioCard.description.description2',
        timeToEndWork: '10 portfolioCard.timeWork.Hours_plural',
    },
    {
        id: 1,
        title: 'portfolioCard.title.title1',
        subTitle: 'portfolioCard.subTitle',
        year: '2019',
        design: '-',
        role: 'portfolioCard.role1',
        tag: 'HTML, CSS',
        platform: 'portfolioCard.platform1',
        type: 'portfolioCard.type2',
        url: 'portfolioCard.urlNotAviable',
        img: img1,
        description: 'portfolioCard.description.description1',
        timeToEndWork: '10 portfolioCard.timeWork.Hours_plural',
    },
];

export default portfolioCard;
