export const atmosphericUpdates = [
    { icon: '🔥', textKey: 'atmosphericUpdates.text1' },
    { icon: '🌌', textKey: 'atmosphericUpdates.text2' },
    { icon: '🧿', textKey: 'atmosphericUpdates.text3' },
    { icon: '🕯', textKey: 'atmosphericUpdates.text4' },
    { icon: '⚙️', textKey: 'atmosphericUpdates.text5' },
    { icon: '🌩', textKey: 'atmosphericUpdates.text6' },
    { icon: '🧊', textKey: 'atmosphericUpdates.text7' },
    { icon: '🕸', textKey: 'atmosphericUpdates.text8' },
    { icon: '🌀', textKey: 'atmosphericUpdates.text9' },
    { icon: '🧠', textKey: 'atmosphericUpdates.text10' },
    { icon: '💡', textKey: 'atmosphericUpdates.text11' },
    { icon: '🛡', textKey: 'atmosphericUpdates.text12' },
    { icon: '🌫️', textKey: 'atmosphericUpdates.text13' },
    { icon: '⚡', textKey: 'atmosphericUpdates.text14' },
    { icon: '🗝', textKey: 'atmosphericUpdates.text15' },
    { icon: '📡', textKey: 'atmosphericUpdates.text16' },
    { icon: '🪞', textKey: 'atmosphericUpdates.text17' },
    { icon: '🌠', textKey: 'atmosphericUpdates.text18' },
    { icon: '💤', textKey: 'atmosphericUpdates.text19' },
    { icon: '📖', textKey: 'atmosphericUpdates.text20' },
    { icon: '🔁', textKey: 'atmosphericUpdates.text21' },
    { icon: '🎭', textKey: 'atmosphericUpdates.text22' },
    { icon: '🔮', textKey: 'atmosphericUpdates.text23' },
    { icon: '🧬', textKey: 'atmosphericUpdates.text24' },
    { icon: '🌑', textKey: 'atmosphericUpdates.text25' },
    { icon: '🚪', textKey: 'atmosphericUpdates.text26' },
];

export default atmosphericUpdates;
